### PR TITLE
Initialize as embulk-util-msgpack built with Gradle

### PR DESCRIPTION
**Pull request by dmikurube**
It is a fork from [MessagePack for Java](https://github.com/msgpack/msgpack-java) v0.8.24 for Embulk plugins to process the MessagePack format without a conflict with the `msgpack-core` dependency from `embulk-spi`.
    
After forking as-is from MessagePack for Java v0.8.24, this pull request includes :
* Removing unnecessary files, including msgpack-jackson,
* Switching the build tool to Gradle,
* Changing the "developers" and "contributors" in pom.xml for the fork,
* Switching the GitHub Actions settings to its own,
* Updating NOTICE for the fork,
* Updating README.md

----

The plan after this initialization would be :
* Move its Java packages from `org.msgpack.*` to `org.embulk.util.msgpack.*`
    * #2 
* Add a support for the new `org.embulk.spi.json.JsonValue` classes
    * #3 
    * See: [EEP-2](https://github.com/embulk/embulk/blob/master/docs/eeps/eep-0002.md)

It will be used in [embulk-parser-msgpack](https://github.com/embulk/embulk-parser-msgpack), and possibly other MessagePack-related plugins.

### CODE REVIEW

**Comment by hiroyuki-sato** [comment]
Not requested review yet. (Just in case) #2 too.

**Comment by dmikurube** [comment]
Yeah, that's intentional. It's yet under consideration.

**Comment by dmikurube** [comment]
Okay, it's ready now -- added @embulk/core-team as a reviewer as the same as other `embulk-util-*` libraries, but we may want to reduce the range later not to spam many people.

Anyway, it is not in a hurry.

**Review by hiroyuki-sato — APPROVED** [review]
LGTM👍

**Comment by dmikurube** [comment]
Thanks!

**Pull request merged**
